name: UNIQLO Automation

on:
  schedule:
    # Run at xx:30 every hour from 03:30 to 21:30 UTC (05:30 to 23:30 CEST)
    - cron: '30 3-21 * * *'

    # Run at xx:00 every hour from 04:00 to 22:00 UTC (06:00 to 00:00 CEST)
    - cron: '0 4-22 * * *'

    # Run at midnight and 00:30 CEST (22:00 and 22:30 UTC)
    - cron: '0 22 * * *'
    - cron: '30 22 * * *'

  workflow_dispatch:

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: ⏳ Random sleep
      run: |
        SECONDS=$((1 + RANDOM % 30))
        echo "⏱ Sleeping for $SECONDS seconds..."
        sleep $SECONDS
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Start timer
      run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
      
    - name: Install Node dependencies
      run: |
        npm init -y
        npm install puppeteer csv-parser json2csv dotenv cheerio
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run Workflow
      run: |
        node fetch-html.js --url "https://www.uniqlo.com/de/de/feature/sale/women" --output product-ids/uniqlo-raw.html
        node html-to-csv.js
        python deal-filter.py
        node fetch-sizes.js || echo "⚠️ fetch-sizes.js failed, continuing..."
        python filter-sizes.py --input product-ids/uniqlo-with-sizes.csv --output product-ids/sizes-filtered.csv
        python send-telegram.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    - name: Insert into DB
      run: python insert-db.py
      env:
        SUPABASE_URL: ${{secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{secrets.SUPABASE_KEY }}
        
    - name: Print total duration
      run: |
        END_TIME=$(date +%s)
        echo "⏱️ Total duration: $((END_TIME - START_TIME)) seconds"
      env:
        START_TIME: ${{ env.START_TIME }}
