name: UNIQLO Automation

on:
  schedule:
    - cron: '*/30 * * * *'  # every 10 minutes
  workflow_dispatch:

jobs:
  run-all:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Node dependencies
      run: |
        npm init -y
        npm install puppeteer csv-parser json2csv dotenv cheerio
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run Workflow
      run: |
        node fetch-html.js --url "https://www.uniqlo.com/de/de/feature/sale/women" --output product-ids/uniqlo-raw.html
        node html-to-csv.js
        python deal-filter.py
        node fetch-sizes.js
        python filter-sizes.py --input product-ids/uniqlo-with-sizes.csv --output product-ids/sizes-filtered.csv
        python send-telegram.py
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
